### ISSUE TITLE
Incorrect display of parenthesis around equation number

### ISSUE THREAD

**Issue by avivrosenberg** [eyalroz/technion-iit-thesis#20]
When compiling the template as-is (no modifications to any source files) I get an incorrect typeset of the parenthesis around equation 3.1.

See attached image:
![screen shot 2017-11-21 at 9 39 34](https://user-images.githubusercontent.com/75639/33060173-0f621e68-cea0-11e7-82fc-67178574ebdf.png)

A while ago I used an older version of this template downloaded from the Technion CS website and it didn't have this issue.

**Comment by eyalroz** [comment]
Acknowledged. This may have happened when I transitioned from pdfTeX + Babel to XeLaTeX + Polyglossia. Will try to look into it this week.

**Comment by eyalroz** [comment]
It was [this issue](https://tex.stackexchange.com/questions/178908/bidi-causes-reversed-parentheses-in-equation-numbers) - and now it's solved, I hope. Please double-check.

**Comment by avivrosenberg** [comment]
It works, thanks 👍
