### ISSUE TITLE
What is the recommended way to produce a technion thesis with Harvard style citations?

### ISSUE THREAD

**Issue by CarbonFixer** [eyalroz/technion-iit-thesis#21]
I could not get natbib to work with this document class.

**Comment by CarbonFixer** [comment]
This seems to work:
1. Adding \usepackage[round, sort]{natbib} to misc/my-general.tex
2. Setting \thesisbibstyle to agsm in thesis-fields.tex
3. Removing all .aux and .bib files before trying to re-compile

**Comment by eyalroz** [comment]
Indeed, removing all auxiliary files before recompiling any LaTeX document is important...

I'll also mention that if your citation style is unusual,, you should check with the graduate studies final-stages secretariat before printing the final copies of the thesis in case they have reservations. Generally there are no specific directions regarding quoting style except it being ["as is customary in scientific articles"](http://www.graduate.technion.ac.il/Heb/Graduation/Thesis_editing.asp) which is pretty vague.
