### ISSUE TITLE
problem adding math formulas in verbatim blocks

### ISSUE THREAD

**Issue by bgalon** [eyalroz/technion-iit-thesis#22]
Hi while using this wonderful project to writing my thesis I needed to write some math in verbatim blocks, found the solution here:
https://tex.stackexchange.com/questions/149710/how-to-write-math-symbols-in-a-verbatim
Not sure if it the best one, but it worked. Will be happy to hear if you have other or better solutions.
Pull request for this fix will follow soon.

**Comment by eyalroz** [comment]
@bgalon : When I wrote my thesis, I used many hundreds of lines of additional definitions and "hacks" beyond what's included the document class and the extra style file. The thing is, they were not particularly related to the document class itself: Either they were entirely general, relevant to any `article`, or `report`, or `book` or any other class - or they were entirely specific to what I needed to do. These should be put into `my-general.tex` or `my-thesis-specific.tex` - in one's own thesis, not in the template. A way of using math within verbatim text falls into the first category, and therefore does not seem to merit inclusion in the template.

Now, you could argue that I've included _too much_ in the template, or rather in `iit-thesis-extra.sty`, and that may be true, but the implication would be moving some of that out into `my-thesis-specific.tex` probably.
