### ISSUE TITLE
Section numbers are opposite

### ISSUE THREAD

**Issue by shaymush** [eyalroz/technion-iit-thesis#27]
![image](https://user-images.githubusercontent.com/7659337/35480928-1c46e782-0422-11e8-8993-586aada5c1a1.png)

Why are the section numbers are opposite? 
How can I change it?

**Comment by eyalroz** [comment]
I don't know, but the numbers are not flipped in the template distributed with the document class, so it is Not My Fault (TM)...

Try creating a [minimum example](https://tex.meta.stackexchange.com/questions/228/ive-just-been-asked-to-write-a-minimal-example-what-is-that) of the issue, and asking about it on tex.stackexchange.com .
