### ISSUE TITLE
hyperref capitalization isn't working

### ISSUE THREAD

**Issue by izikgo** [eyalroz/technion-iit-thesis#29]
The capitalization of hyper references names isn't working (in overleaf) for some reason. As a temporary workaround, I added `\renewcommand*{}`s for the rogue labels in the `my-thesis-specific.tex` file:
```
\renewcommand*{\chapterautorefname}{Chapter}
\renewcommand*{\sectionautorefname}{Section}
\renewcommand*{\subsectionautorefname}{Subsection}
\renewcommand*{\subsubsectionautorefname}{Subsubsection}
```

**Comment by eyalroz** [comment]
Do you also get that when you compile the template locally?

**Comment by eyalroz** [comment]
Also, are you using `iitthesis-extra.sty` ? It has some `\providecommand`'s for that.

**Comment by izikgo** [comment]
I haven't tried it locally. I don't have latex installed on my system.
And yes, I'm using `iitthesis-extra.sty`

**Comment by eyalroz** [comment]
@izikgo : So, the thing is, it may be an Overleaf bug. They have them, apparently. For example, another user was complaining about mis-directed parentheses on Overleaf - which on actual local compilations don't occur. Can you please installing a TeX distribution (e.g. TeXLive on Windows or Linux) and compiling?

**Comment by izikgo** [comment]
I tried that, but battling with the hebrew fonts in horrible. I keep getting:
`xdvipdfmx:fatal: Cannot proceed without the font: C:/ProgramData/MiKTeX/2.9/fonts/type1/public/culmus/DavidCLM-MediumItalic.pfa`
no matter what I try...

**Comment by eyalroz** [comment]
@izikgo : It is challenging, yes; and the Hebrew fonts do need careful installation. Never mind, I'll see what I can do (probably next week).

**Comment by izikgo** [comment]
That's what im trying to do. I just run
`latexmk -xelatex thesis`

**Comment by eyalroz** [comment]
Try `latexmk -xelatex -pdf thesis` perhaps?

**Comment by eyalroz** [comment]
So, I found essentially the same issue on TeX.SX, unanswered:

https://tex.stackexchange.com/questions/423118/xetex-doesnt-find-a-font

Anyway, never mind, I'll try to address the capitalization thing myself, perhaps next week.

**Comment by izikgo** [comment]
`latexmk -xelatex -pdf thesis` doesn't work. 
Thanks, Eyal!

**Comment by izikgo** [comment]
@eyalroz : I tried replacing `David CLM` with `Drugulin CLM` as you suggested.
The document compiles fine now (what a horrible font that is 😛 ), but the original problem is still there: the hyperrefs are not capitalized correctly in section, chapter, etc.
Thanks for your support!

**Comment by eyalroz** [comment]
Now this is more serious. Again, hoping to find the time to look into this next week.

**Comment by eyalroz** [comment]
@izikgo : Sorry for not attending to this earlier. I think it should be ok now.
