### ISSUE TITLE
backref not working

### ISSUE THREAD

**Issue by niremuna** [eyalroz/technion-iit-thesis#30]
I was unable to get backreferences (page numbers + links to where the reference was used in the text).

I have tried the following:
1) adding \usepackage[pagebackref]{hyperref} in my-general.tex
2) adding "pagebackref=true" in hypersetup in iitthesis-extra.sty

**Comment by eyalroz** [comment]
Hello nir,

1. Are you sure this is some issue with the package which prevents back-references from working?
2. Try to create a minimal verifiable example of this happening - cutting out as much as you can,

**Comment by niremuna** [comment]
Hi Eyal and thanks for the great job you did, and also for the quick response.
1. I have tried using hyperref with the pagebackref option in other document and it worked. Hence, I am quite positive that this is indeed an issue.
2. Unfortunately I cannot think of a MWE using the thesis code since it is huge. I can suggest to use the two examples I listed in the previous message.
Many thanks!

**Comment by eyalroz** [comment]
It seems that the pagebackref option needs to be set when loading the package. So, in `misc/iitthesis-extra.sty`, replace:
```
\RequirePackage{hyperref}
```
with:
```
\RequirePackage[pagebackref=true]{hyperref}
```
and that should work. At least, that works for me.

**Comment by niremuna** [comment]
works like a charm, many thanks.
