### ISSUE TITLE
Windows fonts missing David CLM

### ISSUE THREAD

**Issue by Zendelo** [eyalroz/technion-iit-thesis#32]
Hello,
It was quite a while ago now, but when one of the issues I've encountered when using the template in Windows with TexStudio and XeLateX was that the font David CLM couldn't be found/installed.
A solution that worked for me was changing the font to David, simply removing the CLM.

As I've mentioned it was a while ago, so I might be missing some other details/changes that I've made for the template to work properly in Windows.
But just wanted to make sure the fonts solution is documented in the repo.

**Comment by eyalroz** [comment]
And you got this even though the Culmus fonts were actually installed?

Because I specifically list them as a requirement in README.md file

**Comment by Zendelo** [comment]
Yes, but it's hard to answer with full details as I can't recreate it anymore since I don't have that computer anymore. The installation on Windows was different (not sure if it involved MikTex, or something else)
As far as I can remember, the culmus fonts were installed but still the latex compiler couldn't locate the David CLM font.
Either because the Culmus fonts didn't had David CLM (for Windows) or some other reason, either way, changing the default font to David solved it.

The only reference I can find for it now is this:
[http://culmus.sourceforge.net/download.html](http://culmus.sourceforge.net/download.html )
beneath the table the page has a link for Windows users with MikTex that leads to this website:
[http://www.ma.huji.ac.il/~sameti/tex/culmusmiktex.html ](http://www.ma.huji.ac.il/~sameti/tex/culmusmiktex.html )

Which eventually states: 

> The following standard Culmus fonts are included: Aharoni, Caladings, David, Drugulin, Ellinia, Frank Ruehl, Miriam Mono, and Nachlieli

**Comment by eyalroz** [comment]
I see.

Ok. So, it's good that you reported this. I'm going to close the issue now, since it can't be reproduced, but I'll bear this in mind - so that if this comes up for someone else I'll be able to let them know, and perhaps update the documentation.

Also - did you do something else besides change the font family name in `iitthesis.cls`?

**Comment by Zendelo** [comment]
> Also - did you do something else besides change the font family name in iitthesis.cls?
Not that I remember
