### ISSUE TITLE
\qed in proof which finish with math

### ISSUE THREAD

**Issue by infoshoc** [eyalroz/technion-iit-thesis#34]
\qed is added automatically at the end of each proof, but the proofs that end with 'align' environment.

**Comment by eyalroz** [comment]
1. That's not a grammatically valid sentence. 
2. The document class does not even define a proof environment.

**Comment by infoshoc** [comment]
1. I agree, excuse me. 
2. If I understand correctly, [here](https://github.com/eyalroz/technion-iit-thesis/blob/89cf7765535f3eb510e13c53cd5950f5444a6c89/misc/iitthesis-extra.sty#L465) you define amsthm-like proof  for ntheorem

**Comment by eyalroz** [comment]
@infoshoc : Ah, ok, but - that extra stylesheet - you can take it or leave it, it's not necessary.

Anyway, reading your opening sentence again, you're saying that if a proof ends with an `align` envrionment, `\qed`  is not added?

**Comment by eyalroz** [comment]
Anyway, it seems to work for me. See [this Overleaf example](https://www.overleaf.com/read/hydhgjrqrszb).

**Comment by infoshoc** [comment]
Interesting. Your minimal example indeed works. However, when compiling the entire thesis, the problem appears (see page 9 [here](https://www.overleaf.com/read/yfbybscdzwbg)). Probably there is something else that overrides it.

**Comment by eyalroz** [comment]
I'm not seeing a proof ending with an aligned environment on page 9. Where exactly do you mean?

**Comment by infoshoc** [comment]
This piece of code 
```
Here's a proof of the lemma which ends in math:
\begin{proof}%[lem:natural:blowups-preserve-distance-on-average]
\lipsum[2]
\begin{align*}
42
\end{align*}
\end{proof}


And here's a proof of \autoref{thm:first} using the \verb|proofof| environment.
```

Resulting in this output:
![image](https://user-images.githubusercontent.com/3341724/104807165-6a734a80-57e5-11eb-9f1f-74b4d17bc207.png)


(I guess it is not crucial enough, I thought someone just might know the fast solution)

**Comment by eyalroz** [comment]
[Here](https://www.overleaf.com/read/hydhgjrqrszb)'s an example which doesn't even need the `align`.

**Comment by eyalroz** [comment]
Ok, minimal example of the issue: [here](https://www.overleaf.com/read/hydhgjrqrszb). It's some kind of bug with the proof environment.

**Comment by eyalroz** [comment]
So, apparently, this is an `ntheorem` bug. Only with amsthm, or with some code lifted from `amsthm`, can proof-symbol-after-math work.

**Comment by eyalroz** [comment]
Adding notes about this issue and closing it - since it's not a problem with the document class itself.
