### ISSUE TITLE
Incorrect display of parenthesis around equation number #20 persists

### ISSUE THREAD

**Issue by eshalev4** [eyalroz/technion-iit-thesis#36]
I am looking at [your template in overleaf](https://www.overleaf.com/latex/templates/technion-iit-thesis-template/rzqpztzgppwz). It already has the fix, yet, parenthesis around the equation are still not displayed as they should. 

Attached image:
![image](https://user-images.githubusercontent.com/18148244/117145526-ece74080-adbb-11eb-86c6-515ef3cef1b1.png)

**Comment by eyalroz** [comment]
Ah, opened and closed...

well, it works for me on Overlead when I choose TeXLive 2020 as the compiler. Hope you enjoy it :-)

**Comment by eshalev4** [comment]
The two lines you added here do the job. Appearently, the overleaf template lacks them.

**Comment by eyalroz** [comment]
@eshalev4 : "Here" - where?

**Comment by eshalev4** [comment]
Here, on github

**Comment by eyalroz** [comment]
@eshalev4 : You mean the suggestion to use a newer TeXLive version?

**Comment by eshalev4** [comment]
Yes
