### ISSUE TITLE
REferances to subfigures are not in the correct order

### ISSUE THREAD

**Issue by eshalev4** [eyalroz/technion-iit-thesis#37]
Hi,

I am having issues with the references to labels of subfigures. Attached, are example images of the issue. This is the image to be referenced:
![image](https://user-images.githubusercontent.com/18148244/117562036-940df580-b0a4-11eb-998d-737bed6f9f73.png)
This is the actuarial reference:
![image](https://user-images.githubusercontent.com/18148244/117561929-90c63a00-b0a3-11eb-8b1c-9641954c3eb7.png)
The code to reproduce:
```
	    Fig.~\ref{fig:figureb}.
	    \begin{figure}[h]
            \begin{subfigure}{0.5\textwidth}
                \includegraphics[width=0.9\linewidth, height=5cm]{graphics/mygraphic1-for-ps.eps}
                \caption{}\label{fig:figurea}
            \end{subfigure}
            \begin{subfigure}{0.5\textwidth}
                \includegraphics[width=0.9\linewidth, height=5cm]{graphics/mygraphic1-for-ps.eps}
                \caption{}\label{fig:figureb}
            \end{subfigure}
            \caption{\label{fig:Figure}Some caption.}
        \end{figure}
```

This reference should be "Fig. 3.4b". The label of the image should be "Figure :3.4" As this is chapter 3 figure 4.

**Comment by eyalroz** [comment]
This is not part of the template, right? Remember, the document class itself doesn't provide support for everything; whatever depends on other packages is not supported as far as the thesis class is concerned.

Still - can you give exact reproduction instructions as modifications of the thesis template?

**Comment by eshalev4** [comment]
Sure.

I have added lines 16,17 to `my-general.tex`:
```
\usepackage{caption}
\usepackage{subcaption}
```

Also, added the following lines to `mainchap1.tex`, Lines 119-130:
```
Fig.~\ref{fig:figureb}.
	   \begin{figure}[h]
            \begin{subfigure}{0.5\textwidth}
                \includegraphics[width=0.9\linewidth, height=5cm]{graphics/mygraphic1-for-ps.eps}
                \caption{}\label{fig:figurea}
            \end{subfigure}
            \begin{subfigure}{0.5\textwidth}
                \includegraphics[width=0.9\linewidth, height=5cm]{graphics/mygraphic1-for-ps.eps}
                \caption{}\label{fig:figureb}
            \end{subfigure}
            \caption{\label{fig:Figure}Some caption.}
        \end{figure}
```

I do think that the possibility to add figures and subfigures is basic for any thesis. Also, I think this is an issue of collision with the existing tamplet, that willll occur in most cases. Maybe, consider integrating it into the template?

**Comment by eyalroz** [comment]
The figure reference is laid out just fine on my system:

![Screenshot from 2021-05-09 23-57-03](https://user-images.githubusercontent.com/8672255/117586690-62d40a80-b122-11eb-83fd-0043a733206b.png)

I'm using TeXLive 2019 on Devuan GNU/Linux.

**Comment by eyalroz** [comment]
Closed pending further input from reporter.

**Comment by eshalev4** [comment]
I am working on overleaf, with your overleaf template, found in [here](https://www.overleaf.com/latex/templates/technion-iit-thesis-template/rzqpztzgppwz). I have opened a template and you can see the bad referencing in [here](https://www.overleaf.com/read/zwxkvffxcmpc). 

Changes are in `my-general.tex`:

```
% General-purpose definitions and inclusions
% you are using in any document 
% (regardless of its class and style files used),
% e.g. package uses:

%\usepackage{xspace}

% and macros/command defintions:

%\newcommand{\complexityclass}[1]{{\bf #1}\xspace}
%\newcommand{\NPTIME}{\complexityclass{NP}}

% For this template, we'll only have one single command,
% necessary for including graphics...
\usepackage{graphicx}% http://ctan.org/pkg/graphicx
\usepackage{caption}
\usepackage{subcaption}
```

and in the end of `mainchap1.tex`:
```
Figure~\ref{figa}

\begin{figure}[htb]
  \centering
  \begin{subfigure}{0.5\textwidth}
            \includegraphics[width=0.9\linewidth, height=5cm]{graphics/mygraphic1.pdf}
            \caption{}\label{figa}
        \end{subfigure}
        \begin{subfigure}{0.5\textwidth}
            \includegraphics[width=0.9\linewidth, height=5cm]{graphics/mygraphic1.pdf}
            \caption{}\label{figb}
    \end{subfigure}
  \caption{Two circles and a wavy line.}
\end{figure}
```

You can easily reproduce this. The result is:
![image](https://user-images.githubusercontent.com/18148244/126816633-ac14bbb0-cd1a-4b98-ba7a-69f26a2ef343.png)
