### ISSUE TITLE
Publication information order

### ISSUE THREAD

**Issue by guyrosin** [eyalroz/technion-iit-thesis#43]
Hi,
Thanks a lot for this awesome template!
Is it possible to sort the publication information chronologically?
Currently, because the thesis bibliography style is set to `alpha`, the list is ordered alphabetically.
But that's not ideal. I think a chronological order would be more intuitive.
Example:
![image](https://user-images.githubusercontent.com/1250162/151366179-feababe8-604e-4e36-acb8-74240d12e6b7.png)

**Comment by eyalroz** [comment]
First, .please check whether the graduate school guidelines say anything about the sort order. I think they don't, but let's double-check.

As to the question itself: The answer is that it's as possible as it is to sort any bibliography chronologically. I think you'll probably need to alter the `alpha` style.

**Comment by guyrosin** [comment]
Thanks for the fast response!
The guidelines don't say anything about the publications order.
I tried changing the bibliographystyle (in `iitthesis-extra.sty` and `thesis-fields.tex`) but couldn't make it work as I wanted

**Comment by guyrosin** [comment]
Sorry, I don't follow. 
It doesn't seem like the publication year affects the order of the bibliography at all - you can see that in the screenshot in the first comment. 
The bibliography appears to be sorted alphabetically (by the authors), because of the `alpha` style.

**Comment by eyalroz** [comment]
If you build the thesis in this package as-is, the first item shown is "Dynamic lettuce programming" from 2010. If you change its publication year to 2015, then it's shown second, after "Efficient solutions of foliage-related problems" from 2011.

**Comment by guyrosin** [comment]
You're right! But when I add to that bib file a paper with a different author name, I get unexpected results...
![image](https://user-images.githubusercontent.com/1250162/151677187-0364e06e-68ce-4ea4-964d-ab09930ce5e8.png)

This is the bib content:
```
@inproceedings{firstwork-foracks,
  author     = {Jane Smith and Mish Talem},
  title      = {Dynamic lettuce programming},
  booktitle  = {Proceedings of AGRIALGO 2010},
  year       = {2012},
  location   = {Somewhere, NY, USA},
  pages      = {123--154},
  publisher  = {Springer},
  location   = {Berlin / Heidelberg},
}

@incollection{secondwork-foracks,
  author     = {Big Shot and Mish Talem},
  title      = {Efficient solutions of foliage-related problems},
  booktitle  = {Greenleaf algorithms},
  year       = {2011},
  pages      = {239--254},
  series     = {Computer Science and Agriculture},
  editor     = {Eddy Kramer},
  publisher  = {Addison-Wesley},
  volume     = {231},
}

@incollection{secondwork-foracks2,
  author     = {Zig Zog and Mish Talem},
  title      = {Efficient solutions of foliage-related problems},
  booktitle  = {Greenleaf algorithms},
  year       = {2010},
  pages      = {239--254},
  series     = {Computer Science and Agriculture},
  editor     = {Eddy Kramer},
  publisher  = {Addison-Wesley},
  volume     = {231},
}
```

**Comment by eyalroz** [comment]
The answer indeed has to do with the bibliography style. Have a look at the `.bbl` file below; do you see the keys (which would be used if the works were cited? As you suspected, the author name comes first.

So, we do need to do something here.
```
\begin{thebibliography}{ZT10}

\bibitem[ST11]{secondwork-foracks}
Big Shot and Mish Talem.
\newblock Efficient solutions of foliage-related problems.
\newblock In Eddy Kramer, editor, {\em Greenleaf algorithms}, volume 231 of
  {\em Computer Science and Agriculture}, pages 239--254. Addison-Wesley, 2011.

\bibitem[ST12]{firstwork-foracks}
Jane Smith and Mish Talem.
\newblock Dynamic lettuce programming.
\newblock In {\em Proceedings of AGRIALGO 2010}, pages 123--154. Springer,
  2012.

\bibitem[ZT10]{thirdwork-foracks}
Zig Zog and Mish Talem.
\newblock Efficient solutions of foliage-related problems.
\newblock In Eddy Kramer, editor, {\em Greenleaf algorithms}, volume 231 of
  {\em Computer Science and Agriculture}, pages 239--254. Addison-Wesley, 2010.

\end{thebibliography}
```

**Comment by guyrosin** [comment]
Great :)
I tried modifying the `bibliographystylepubinfo` command in line 622 of `iitthesis-extra.sty`.
Using the `unsrt` bibliographystyle should be perfect for us (it uses the publication order as written in the bib file)
But it seems every style except of `alpha` results in an unformatted bibliography - see below.
So I guess the `alpha` style is somewhat hardcoded...
![image](https://user-images.githubusercontent.com/1250162/151678643-7537040e-83ae-4184-9066-9fb666958569.png)

**Comment by eyalroz** [comment]
Ok, I'm going to customize `alpha` to make it unsorted. That's not a perfect solution, but at least it would let everyone control the order the way they want it (so it could be by importance, by date, by reverse date etc.)

**Comment by guyrosin** [comment]
Sounds great, thanks!

**Comment by eyalroz** [comment]
@guyrosin : Try my latest push.

**Comment by guyrosin** [comment]
Perfect. Thank you!
