### ISSUE TITLE
Using biblatex/biber for references

### ISSUE THREAD

**Issue by haggaie** [eyalroz/technion-iit-thesis#44]
I prefer biblatex over BibTeX when I can as it allows more control over the results with fewer manual changes to bib files. Do you think the template should support it as an alternative or instead of BibTeX?

**Comment by eyalroz** [comment]
I have never given this any thought, since since I was young I only ever knew about using `\bibliography` and did not realize alternative tools used different syntax.

Anyway...

* What's the popularity situation of biblatex these days? In general, and in the department?
* When people are taught LaTeX (e.g. at the department of CS), are they taught to use bibtex or biblatex?
* If supporting both bibtex and biblatex would require using commands custom to the document class, I would be hesitant. Otherwise I don't mind.

**Comment by haggaie** [comment]
I'm not sure how one measures popularity of latex packages. I imagine Overleaf would have such information, or someone could scrape github/arxiv for it, but I couldn't find it.

I think the default anyone learns is bibtex, but Overleaf teaches biblatex first (https://www.overleaf.com/learn/latex/Bibliography_management_in_LaTeX), and specifically recommend biblatex over bibtex in their [bibtex documentation](https://www.overleaf.com/learn/latex/Bibliography_management_with_bibtex).

As for the relevant control, it is relatively easy to customize the output, changing for example the citation style, sorting order, or turning some fields on and off (DOI or URLs). It is also possible to write macros for more advanced control, e.g., turn off URLs for entries with DOI, unless they are of type @misc. I'm sure you could achieve this also by modifying natbib styles, but here you can do this using LaTeX commands.

Biblatex also has built-in support for multiple bibliographies, so I think it can manage the front-page bibliography as well.

**Comment by eyalroz** [comment]
Ok, let's say I'm convinced.

Would you be willing to create a PR which:

1. Maintains the current bibliography styles (more or less).
2. Covers the publication-info extra bibliography <- Possibly moving things from `iitthesis-extra.sty` into the document class if necessary
3. Is compatible with what we have in `iitthesis-extra.sty`?
4. Adds some lines mentioning biblatex and its use targeted at people who have been using bibtex? (Naturally, no more explanations than they would need to keep them out of trouble when using the thesis class)

**Comment by haggaie** [comment]
Sure. I'm using biblatex for my own thesis, so I can try cleaning up the code for a PR.

By the way, is there guidance on the bibliography style from the graduate school? Should I just try to match what the template currently generates?

**Comment by eyalroz** [comment]
@haggaie : There are no bibliography style guidelines that I'm aware of, which is a bit strange. Try to match what the template generates at the moment, unless you also believe that's a bad idea, in which case we can discuss that in a separate issue.
