### ISSUE TITLE
New glossary fails on overleaf

### ISSUE THREAD

**Issue by ItayTsabary** [eyalroz/technion-iit-thesis#49]
Hi,

Thanks for maintaining this life-saving repo!

It seems the last patch of the glossary (Feb 1) breaks the overleaf build:

1. The "Notation and Abbreviations" page (13 in the pdf) gives an error message about failing to find an "output.not" file. 
2. This issue is also reported in the output.log file.

I'm attaching several of the log files that I thought are relevant, please let me know if anything else is needed.

MWE -- the template files themselves, no additional files or modifications are needed.

I'm running on overleaf with xelatex and the 2018 version.

The issue is not reproduced while using the previous version.

Thanks,
Itay

[bugreport.zip](https://github.com/eyalroz/technion-iit-thesis/files/8152368/bugreport.zip)
[output.pdf](https://github.com/eyalroz/technion-iit-thesis/files/8152369/output.pdf)

**Comment by ItayTsabary** [comment]
Some further debugging:

The required ```output.not``` file is not created with the current setup.

I found two ways to force its creation, using the ```\printglossaries``` macro from ```glossaries-extra```

1. Add ```\printglossaries``` just after ```\makefrontmatter``` -- this will create ```output.not```, resulting with a successful glossary at the designated page, but will also result with an additional glossary being included. However, commenting out ```\printglossaries``` and re-running (without deleting the cached files, i.e., the created ```output.not```) yield the correct format.

2. Replace ```\printglossary``` with ```\printglossaries``` in the cls file -- this successfully builds the glossary at the correct place, but omits the page numbers of the first use.

**Comment by eyalroz** [comment]
Thanks for reporting this. I'll try to find the time to work on this, maybe over the weekend. @haggaie FYI, and I remember I owe you an answer on your latest comment, and to wrap up the work on #48 .

**Comment by eyalroz** [comment]
@ItayTsabary : Well need to think about why output.not is not created, and figure out a way to ensure it's created without needing the workarounds you found.

**Comment by haggaie** [comment]
Hi, I couldn't reproduce the issue for some reason. I imported the template from GitHub, and it seemed to create the abbreviations and notations page correctly.

I didn't find an updated template within Overleaf. @ItayTsabary, did you upload the files manually? Is it possible you are missing the .latexmkrc file?

**Comment by ItayTsabary** [comment]
Yes, that was the issue! Ugh. It seems my ```.gitignore``` file kept the ```.latexmkrc``` excluded from overleaf. Thanks, and sorry for wasting your time on this.

**Comment by eyalroz** [comment]
I should mention that the repository's `.gitignore` does not contain a rule which matches `.latexmkrc`.

Is there something we should do to prevent this from happening to other people?

**Comment by haggaie** [comment]
I think it might be possible to name it without the dot, so it won't be
hidden, but I haven't tried it.

**Comment by ItayTsabary** [comment]
> 

I think it is ignored due to line 114

**Comment by eyalroz** [comment]
@ItayTsabary : Well, that entry would match it... on the other hand, `git status` shows changes to `.latexmkrc`. Still, I should probably remove line 114 just to be on the safe side.

**Comment by ItayTsabary** [comment]
I believe it shows changes if you explicitly added the file to the repo. 

Also probably why I had it ignored -- your repo tracked it, my new repo didn't.

**Comment by eyalroz** [comment]
That's probably the case, but I want to avoid other people experiencing this pitfall, hence the commit.
