### ISSUE TITLE
Section numbering appearing before chapter number in titles, including figure and table names

### ISSUE THREAD

**Issue by galiff** [eyalroz/technion-iit-thesis#53]
this also appears in the pdf example, is it a bug?

**Comment by eyalroz** [comment]
It is likely a bug with your TeX distribution, or a compatibility failure. That does not typically occur.

**Comment by eyalroz** [comment]
I remember some people had similar issues on Overleaf, and it had to do with the TeXLive version in use. Could you try playing with that?

**Comment by galiff** [comment]
going from the default (2016) to the newest Tex Live (version 2022) fixed
it. Thank you so much!
