### ISSUE TITLE
Labelling using equation issue

### ISSUE THREAD

**Issue by dannavon** [eyalroz/technion-iit-thesis#54]
Hello,
First, thanks for maintaining this thesis repo!

I am trying to label an equation like that:
\begin{equation} \label{eq:1}
\sum_{i=0}^{\infty} a_i x^i
\end{equation}
Equation \ref{eq:1} is a typical power series.

But for some reason, it doesn't work.
If I am changing \begin{equation} to \begin{align} it does work.

I reproduced this error; see the first abstract page on a blank thesis project:
https://www.overleaf.com/8526394536qxkkmncfhpqh

**Comment by dannavon** [comment]
I found a workaround - 
I put this line in comment:
%\RequirePackage[hyperref,thmmarks]{ntheorem}

And uncomment:
\RequirePackage{amsthm}

Although the labeling works now, I have different problems with some figures, and I am not sure how they are related.

**Comment by eyalroz** [comment]
Well, that workaround messes with other features that we want to have used in the thesis (like hyperref linking compatbility). I need to look into this further.

What I can tell you is that when building with TeXLive 2022 on a (typical) Linux system, I get no such error. Have you tried building it outside of overleaf?

**Comment by dannavon** [comment]
I didn't try outside Overleaf, but I tried multiple TeXLive versions and none of them seems to work.

**Comment by OriRoth** [comment]
Here they suggest to add `amsmath`: `\RequirePackage[hyperref,thmmarks,amsmath]{ntheorem}`

https://tex.stackexchange.com/questions/127420/thmmarks-in-ntheorem-causing-trouble-with-numbers-in-equations
