### ISSUE TITLE
Bibliography - Importing Mendeley references

### ISSUE THREAD

**Issue by ohadme** [eyalroz/technion-iit-thesis#55]
Hello,
I've successfully linked Mendeley to Overleaf and imported my references to general.bib. However, I'm encountering issues when using the technion-iit-thesis template with Mendeley references.

Has anyone successfully integrated Mendeley with this template and used the references?
How can I ensure the references are displayed in numeric order?

Thanks for any insights!

**Comment by eyalroz** [comment]
> Has anyone successfully integrated Mendeley with this template and used the references?

Users of the thesis class rarely share anything with me, e.g. what other LaTeX-related mechanisms they use. So, I don't know.

> How can I ensure the references are displayed in numeric order?

I'm not sure what you mean. How are Mendeley references different than any other reference you put in your `.bib` files?

**Comment by ohadme** [comment]
Thank you for getting back to me so promptly. Mendeley provides a feature to update the bibliography, as detailed in this [Overleaf guide](https://www.overleaf.com/learn/how-to/How_to_link_your_Overleaf_account_to_Mendeley_and_Zotero).

I'm uncertain about the exact differences, but when I use \cite{}, the template ceases to display the Bibliography page. Additionally, the reference appears as the name of the reference rather than its number.

**Comment by eyalroz** [comment]
If you can provide a syntactically-valid `general.bib` file that causes these phenomena when building the sample thesis - I can look into this. Otherwise - it's just yet-anoter-LaTeX-problem...

**Comment by ohadme** [comment]
Thanks 
Here is a link for the general.bib https://drive.google.com/file/d/15oLQE4jEOP_RSgqIUlDyL2JrfRjjjq1H/view?usp=sharing

**Comment by eyalroz** [comment]
Your `general.bib` is missing a `}` at the end of the last item. When I add the `}` - the sample thesis compiles fine.
