### ISSUE TITLE
[Overleaf] Figure captions are not written correctly (I think)

### ISSUE THREAD

**Issue by natanhoffmann** [eyalroz/technion-iit-thesis#58]
Figures in the main body show incorrect captions. For instance, the following Latex code:

```
\begin{figure}[h!]
    \centering
    \includegraphics[width=0.5\textwidth]{main/figures/pathsToTransition.PNG}
    \caption{Paths of boundary-layer transition. Figure taken from Fedorov \cite{fedorov2011transition}.}
    \label{fig:main/figures/pathsToTransition}
\end{figure}
```

produces the following caption:
![Screenshot 2024-06-21 at 17 07 45](https://github.com/eyalroz/technion-iit-thesis/assets/125212924/338f5383-a8ac-4c47-9c5f-555002620c34)

I believe the colon should be after the number 1.1.

Oddly enough, figures placed in the Appendices have the correct caption:

![Screenshot 2024-06-21 at 17 09 41](https://github.com/eyalroz/technion-iit-thesis/assets/125212924/8856a2fe-d5d0-4e60-a0ae-9c64c9396221)

**Comment by natanhoffmann** [comment]
Note that I am using the Overleaf template to write my thesis, so if I can see the relevant code change for this fix so that I can fix it manually, I would really appreciate it!

**Comment by eyalroz** [comment]
I've note gotten a complaint about this before; and when I build the thesis - using the code on this repository, and texlive package version 2023.20240207-1, I can't reproduce:
![Screenshot from 2024-06-21 17-21-18](https://github.com/eyalroz/technion-iit-thesis/assets/8672255/2b2b183a-58f3-4705-911e-4b547eaecdce)

**Comment by natanhoffmann** [comment]
Do you know if the template on Overleaf is up-to-date?

**Comment by natanhoffmann** [comment]
I think I figured it out! My mistake. I saw in the README that XeLateX must be used. But I did not notice that the TeX Live version should be 2018. It seems in Overleaf this was 2016 by default!

**Comment by eyalroz** [comment]
I'm glad you figured it out. Would appreciate it if you tried to get your department and/or the graduate school to devote some resources to help me with package maintenance and updates, and even more than that - informing graduate researchers in different departments about this thesis template instead of each of them having to figure it out themselves.
