### ISSUE TITLE
Empty bibliography

### ISSUE THREAD

**Issue by ohadlor** [eyalroz/technion-iit-thesis#61]
Both the butcheredbibliography and the regular bibliography are not displayed. This is the case also for the code as is, before any changes. Using miktex and xelatex. biblatex is installed. Not sure what might be missing. The .bbl is created but remains empty

**Comment by eyalroz** [comment]
>  are not displayed.

Well, they are displayed for most users (and for myself)... so, perhaps you can help me pin down the exact. Please provide:

1. OS information
2. CPU architecture
3. Exact version information for MikTeX and anything else that might be relevant
4. Any changes you've made to your TeX installation, e.g. manual additions and changes

... which may allow me to reproduce the issue.

**Comment by ohadlor** [comment]
Solved.
The issue was that I am using texstudio and compiled via xelatex and not latexmk -xelatex.
Thanks again for your time

**Comment by eyalroz** [comment]
> Solved. The issue was that I am using texstudio and compiled via xelatex and not latexmk -xelatex. Thanks again for your time

Do you think I could make it clearer that the thesis must be _fully_, _comprehensively_ compiled? e.g. in the sample thesis text or in the README? A concrete suggestion could be helpful...

**Comment by ohadlor** [comment]
I think adding to the README is the best choice, I would clarify that you _need_ to use latexmk with xelatex as the compiler option .  That just running xelatex will not compile the bibliography correctly.
